spring:
    application.name: kafka-stream-example

    #    config:
    #      activate:
    #          on-profile: default

    cloud:
        stream:
            default:
                default-binder: local-kafka

            binders:
                local-kafka:
                    type: kafka
                    environment:
                        spring.cloud.stream.kafka.binder.broker: localhost:9092

            bindings:
                # producer
                basicProducer-out-0:
                    binder: local-kafka
                    destination: chat # 토픽
                    content-type: application/json

                # consumer
                basicProducer-in-0:
                    binder: local-kafka
                    group: ${spring.config.activate.on-profile}.${spring.application.name}
                    destination: chat # 토픽
                    consumer:
                      max-attempts: 3

            # kafka setting
            kafka:
                bindings:
                    basicProducer-in-0:
                        consumer:
                            ack-mode: record

        function:
            definition:  basicProducer;


server:
    shutdown: graceful

